import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.scss";
import "bootstrap/dist/css/bootstrap.css";
import Image from "next/image";
import axios from "axios";
import { useState } from "react";
import { Button, TextField, FormControlLabel, Checkbox } from "@mui/material";
import { useRouter } from "next/router";
//import aboutUsSideImage from "../public/Pictures/";
import registerHomeBackground from "../public/Pictures/registerHomeBackground.jpg";
import { useLogIn } from "@/context/LogIn";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [email, setEmail] = useState(null);
  const [password, setPassword] = useState(null);
  const [verifyPassword, setVerifyPassword] = useState(null);
  const [name, setName] = useState(null);
  const [checked, setchecked] = useState(false);
  const { isLoggedIn, setIsLoggedIn } = useLogIn();

  const router = useRouter();
  const url = process.env.NEXT_PUBLIC_URL;

  const insertUser = async () => {
    axios
      .post(`${url}/api/users/add`, {
        email: email,
        password: password,
      })
      .then(() => {})
      .catch((e) => {
        console.log("Couldn't register user");
      });
  };

  const handleEmail = (value) => {
    if (value.match(/^\w+([.-]?\w+)@\w+([.-]?\w+)(.\w{2,3}).\w+([.-]?\w+)+$/)) {
      setEmail(value);
    } else {
      setEmail(null);
    }
  };

  const handlePassword = (value) => {
    if (value == password) {
      setVerifyPassword(value);
    } else {
      setVerifyPassword(null);
    }
  };

  const addNewsletter = async () => {
    if (checked) {
      const data = { name: name, email: email };
      axios
        .post(`${url}/api/newsLetter/addsub`, data)
        .then(() => {})
        .catch((error) => {
          console.error(error);
        });
    }
  };
  const handleSubmit = () => {
    addNewsletter();
    insertUser();
    //.then waits to insert the user to database , chack if succesful then does the function
    router.push("/Articles");
  };
  return (
    <>
      <Head>
        <title>Article Conclave</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Logo.svg" />
      </Head>
      <main className={styles.main}>
        {/* about us section */}
        <div className={styles.aboutUsContainer}>
          <div className={styles.heroSection}>
            <div className={styles.welcome}>
              <h1 className={styles.title}>
                Welcome to<br></br> Aritcle Conclaive
              </h1>
            </div>
          </div>
        </div>

        {/* about us texyt */}
        <div className={styles.aboutUsTxtContainer}>
          <h2 className={styles.aboutUsTitle}>About Us</h2>
          <p className={styles.aboutUsTxt}>
            article conclave is a Professional Educational Platform. Here we
            will provide you only interesting content, which you will like very
            much. We're dedicated to providing you the best of articles, with a
            focus on dependability and stories, tutorials. We're working to turn
            our passion for discovery, into a booming online website. We hope
            you enjoy our articles, as much as we enjoy offering them to you.
          </p>
        </div>

        {!isLoggedIn && (
          <>
            {/* register home section */}
            <div className={styles.registerContainer}>
              <div className={styles.registerForm}>
                <h2 className={styles.aboutUsTitle}>Register</h2>
                <form className={styles.form}>
                  <TextField
                    className={styles.txtField}
                    label="Name"
                    variant="outlined"
                    onChange={(e) => {
                      setName(e.target.value);
                    }}
                  />
                  <TextField
                    className={styles.txtField}
                    label="Email"
                    variant="outlined"
                    //onClicck when a function needs a parameter
                    onChange={(e) => {
                      handleEmail(e.target.value);
                    }}
                  />
                  <div id="emailHelp" className={styles.txtField}>
                    We'll never share your email with anyone else.
                  </div>

                  <TextField
                    className={styles.txtField}
                    label="Password"
                    variant="outlined"
                    type="password"
                    onChange={(e) => {
                      setPassword(e.target.value);
                    }}
                  />

                  <TextField
                    className={styles.txtField}
                    label="Verify Password"
                    variant="outlined"
                    type="password"
                    onChange={(e) => {
                      handlePassword(e.target.value);
                    }}
                  />
                  <div className="mb-3 form-check">
                    <FormControlLabel
                      control={
                        <Checkbox
                          onChange={(event) => setchecked(event.target.checked)}
                        />
                      }
                      label="Subscribe to newsletter"
                    />
                  </div>
                  <Button
                    variant="contained"
                    disabled={
                      password == null ||
                      email == null ||
                      verifyPassword == null
                    }
                    //onClick when a fuction doen't need a parameter
                    onClick={handleSubmit}
                  >
                    Sign Up
                  </Button>
                </form>
              </div>
              <div className={styles.imgRegister}>
                <Image
                  src={registerHomeBackground}
                  width={320}
                  height={488.75}
                  alt="Register image"
                />
              </div>
            </div>
          </>
        )}
      </main>
    </>
  );
}
